services:
  db-dev:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DATABASE: dev
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password123
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
